server: 
   port: 8086

spring:
    datasource:
          url: jdbc:mysql://localhost:3306/thoughtfocus
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: Venky@153
    jpa:
          hibernate:
                 ddl-auto: update
               
    mvc:
          pathmatch:
                 matching-strategy : ANT_PATH_MATCHER
#logging.level.org.springframework=DEBUG

logging:
     level:
           com:
                 thoughtfocus: DEBUG
     pattern:
           console: "%d{yyyy-MM-dd HH:mm:ss} - %m %n"

